let p5FunctionsAndConstants = [
    "ADD",
    "ALT",
    "ARROW",
    "AUDIO",
    "AUTO",
    "AXES",
    "BACKSPACE",
    "BASELINE",
    "BEVEL",
    "BEZIER",
    "BLEND",
    "BLUR",
    "BOLD",
    "BOLDITALIC",
    "BOTTOM",
    "BURN",
    "CENTER",
    "CHAR",
    "CHORD",
    "CLAMP",
    "CLOSE",
    "CONTAIN",
    "CONTROL",
    "CORNER",
    "CORNERS",
    "COVER",
    "CROSS",
    "CURVE",
    "DARKEST",
    "DEGREES",
    "DEG_TO_RAD",
    "DELETE",
    "DIFFERENCE",
    "DILATE",
    "DODGE",
    "DOWN_ARROW",
    "ENTER",
    "ERODE",
    "ESCAPE",
    "EXCLUSION",
    "FALLBACK",
    "FILL",
    "FLAT",
    "FLOAT",
    "GRAY",
    "GRID",
    "HALF_FLOAT",
    "HALF_PI",
    "HAND",
    "HARD_LIGHT",
    "HSB",
    "HSL",
    "IMAGE",
    "IMMEDIATE",
    "INVERT",
    "ITALIC",
    "LABEL",
    "LANDSCAPE",
    "LEFT",
    "LEFT_ARROW",
    "LIGHTEST",
    "LINEAR",
    "LINES",
    "LINE_LOOP",
    "LINE_STRIP",
    "MIRROR",
    "MITER",
    "MOVE",
    "MULTIPLY",
    "NEAREST",
    "NORMAL",
    "OPAQUE",
    "OPEN",
    "OPTION",
    "OVERLAY",
    "P2D",
    "PI",
    "PIE",
    "POINTS",
    "PORTRAIT",
    "POSTERIZE",
    "PROJECT",
    "QUADRATIC",
    "QUADS",
    "QUAD_STRIP",
    "QUARTER_PI",
    "RADIANS",
    "RADIUS",
    "RAD_TO_DEG",
    "REMOVE",
    "REPEAT",
    "REPLACE",
    "RETURN",
    "RGB",
    "RGBA",
    "RIGHT",
    "RIGHT_ARROW",
    "ROUND",
    "SCREEN",
    "SHIFT",
    "SMOOTH",
    "SOFT_LIGHT",
    "SQUARE",
    "STROKE",
    "SUBTRACT",
    "TAB",
    "TAU",
    "TESS",
    "TEXT",
    "TEXTURE",
    "THRESHOLD",
    "TOP",
    "TRIANGLES",
    "TRIANGLE_FAN",
    "TRIANGLE_STRIP",
    "TWO_PI",
    "UNSIGNED_BYTE",
    "UNSIGNED_INT",
    "UP_ARROW",
    "VERSION",
    "VIDEO",
    "WAIT",
    "WEBGL",
    "WEBGL2",
    "WORD",
    "abs",
    "accelerationX",
    "accelerationY",
    "accelerationZ",
    "acos",
    "alpha",
    "ambientLight",
    "ambientMaterial",
    "angleMode",
    "append",
    "applyMatrix",
    "arc",
    "arrayCopy",
    "asin",
    "atan",
    "atan2",
    "background",
    "beginClip",
    "beginContour",
    "beginGeometry",
    "beginShape",
    "bezier",
    "bezierDetail",
    "bezierPoint",
    "bezierTangent",
    "bezierVertex",
    "blend",
    "blendMode",
    "blue",
    "boolean",
    "box",
    "brightness",
    "buildGeometry",
    "byte",
    "callRegisteredHooksFor",
    "camera",
    "ceil",
    "char",
    "circle",
    "clear",
    "clearDepth",
    "clearStorage",
    "clip",
    "color",
    "colorMode",
    "concat",
    "cone",
    "constrain",
    "copy",
    "cos",
    "createA",
    "createAudio",
    "createButton",
    "createCamera",
    "createCanvas",
    "createCapture",
    "createCheckbox",
    "createColorPicker",
    "createDiv",
    "createElement",
    "createFileInput",
    "createFilterShader",
    "createFramebuffer",
    "createGraphics",
    "createImage",
    "createImg",
    "createInput",
    "createNumberDict",
    "createP",
    "createRadio",
    "createSelect",
    "createShader",
    "createSlider",
    "createSpan",
    "createStringDict",
    "createVector",
    "createVideo",
    "createWriter",
    "cursor",
    "curve",
    "curveDetail",
    "curvePoint",
    "curveTangent",
    "curveTightness",
    "curveVertex",
    "cylinder",
    "day",
    "debugMode",
    "degrees",
    "deltaTime",
    "describe",
    "describeElement",
    "deviceOrientation",
    "directionalLight",
    "displayDensity",
    "displayHeight",
    "displayWidth",
    "dist",
    "downloadFile",
    "ellipse",
    "ellipseMode",
    "ellipsoid",
    "emissiveMaterial",
    "encodeAndDownloadGif",
    "endClip",
    "endContour",
    "endGeometry",
    "endShape",
    "erase",
    "exitPointerLock",
    "exp",
    "fill",
    "filter",
    "float",
    "floor",
    "focused",
    "fract",
    "frameCount",
    "frameRate",
    "freeGeometry",
    "frustum",
    "fullscreen",
    "get",
    "getFilterGraphicsLayer",
    "getFrameRate",
    "getItem",
    "getTargetFrameRate",
    "getURL",
    "getURLParams",
    "getURLPath",
    "green",
    "gridOutput",
    "height",
    "hex",
    "hour",
    "httpDo",
    "httpGet",
    "httpPost",
    "hue",
    "image",
    "imageLight",
    "imageMode",
    "int",
    "isKeyPressed",
    "isLooping",
    "join",
    "key",
    "keyCode",
    "keyIsDown",
    "keyIsPressed",
    "lerp",
    "lerpColor",
    "lightFalloff",
    "lightness",
    "lights",
    "line",
    "linePerspective",
    "loadBytes",
    "loadFont",
    "loadImage",
    "loadJSON",
    "loadModel",
    "loadPixels",
    "loadShader",
    "loadStrings",
    "loadTable",
    "loadXML",
    "log",
    "loop",
    "mag",
    "map",
    "match",
    "matchAll",
    "max",
    "metalness",
    "millis",
    "min",
    "minute",
    "model",
    "month",
    "mouseButton",
    "mouseIsPressed",
    "mouseX",
    "mouseY",
    "movedX",
    "movedY",
    "nf",
    "nfc",
    "nfp",
    "nfs",
    "noCanvas",
    "noCursor",
    "noDebugMode",
    "noErase",
    "noFill",
    "noLights",
    "noLoop",
    "noSmooth",
    "noStroke",
    "noTint",
    "noise",
    "noiseDetail",
    "noiseSeed",
    "norm",
    "normal",
    "normalMaterial",
    "orbitControl",
    "ortho",
    "pAccelerationX",
    "pAccelerationY",
    "pAccelerationZ",
    "pRotateDirectionX",
    "pRotateDirectionY",
    "pRotateDirectionZ",
    "pRotationX",
    "pRotationY",
    "pRotationZ",
    "panorama",
    "perspective",
    "pixelDensity",
    "pixels",
    "plane",
    "pmouseX",
    "pmouseY",
    "point",
    "pointLight",
    "pop",
    "popMatrix",
    "popStyle",
    "pow",
    "print",
    "push",
    "pushMatrix",
    "pushStyle",
    "pwinMouseX",
    "pwinMouseY",
    "quad",
    "quadraticVertex",
    "radians",
    "random",
    "randomGaussian",
    "randomSeed",
    "rect",
    "rectMode",
    "red",
    "redraw",
    "registerPromisePreload",
    "removeElements",
    "removeItem",
    "requestPointerLock",
    "resetMatrix",
    "resetShader",
    "resizeCanvas",
    "reverse",
    "rotate",
    "rotateX",
    "rotateY",
    "rotateZ",
    "rotationX",
    "rotationY",
    "rotationZ",
    "round",
    "saturation",
    "save",
    "saveCanvas",
    "saveFrames",
    "saveGif",
    "saveJSON",
    "saveJSONArray",
    "saveJSONObject",
    "saveStrings",
    "saveTable",
    "scale",
    "second",
    "select",
    "selectAll",
    "set",
    "setAttributes",
    "setCamera",
    "setFrameRate",
    "setMoveThreshold",
    "setShakeThreshold",
    "shader",
    "shearX",
    "shearY",
    "shininess",
    "shorten",
    "shuffle",
    "sin",
    "smooth",
    "sort",
    "specularColor",
    "specularMaterial",
    "sphere",
    "splice",
    "split",
    "splitTokens",
    "spotLight",
    "sq",
    "sqrt",
    "square",
    "storeItem",
    "str",
    "stroke",
    "strokeCap",
    "strokeJoin",
    "strokeWeight",
    "subset",
    "tan",
    "text",
    "textAlign",
    "textAscent",
    "textDescent",
    "textFont",
    "textLeading",
    "textOutput",
    "textSize",
    "textStyle",
    "textWidth",
    "textWrap",
    "texture",
    "textureMode",
    "textureWrap",
    "tint",
    "torus",
    "touches",
    "translate",
    "triangle",
    "trim",
    "turnAxis",
    "unchar",
    "unhex",
    "updatePixels",
    "vertex",
    "webglVersion",
    "width",
    "winMouseX",
    "winMouseY",
    "windowHeight",
    "windowWidth",
    "writeFile",
    "year"
]

let p5jsFunctions = [
    "abs",
    "accelerationX",
    "accelerationY",
    "accelerationZ",
    "acos",
    "alpha",
    "ambientLight",
    "ambientMaterial",
    "angleMode",
    "append",
    "applyMatrix",
    "arc",
    "arrayCopy",
    "asin",
    "atan",
    "atan2",
    "background",
    "beginClip",
    "beginContour",
    "beginGeometry",
    "beginShape",
    "bezier",
    "bezierDetail",
    "bezierPoint",
    "bezierTangent",
    "bezierVertex",
    "blend",
    "blendMode",
    "blue",
    "boolean",
    "box",
    "brightness",
    "buildGeometry",
    "byte",
    "callRegisteredHooksFor",
    "camera",
    "ceil",
    "char",
    "circle",
    "clear",
    "clearDepth",
    "clearStorage",
    "clip",
    "color",
    "colorMode",
    "concat",
    "cone",
    "constrain",
    "copy",
    "cos",
    "createA",
    "createAudio",
    "createButton",
    "createCamera",
    "createCanvas",
    "createCapture",
    "createCheckbox",
    "createColorPicker",
    "createDiv",
    "createElement",
    "createFileInput",
    "createFilterShader",
    "createFramebuffer",
    "createGraphics",
    "createImage",
    "createImg",
    "createInput",
    "createNumberDict",
    "createP",
    "createRadio",
    "createSelect",
    "createShader",
    "createSlider",
    "createSpan",
    "createStringDict",
    "createVector",
    "createVideo",
    "createWriter",
    "cursor",
    "curve",
    "curveDetail",
    "curvePoint",
    "curveTangent",
    "curveTightness",
    "curveVertex",
    "cylinder",
    "day",
    "debugMode",
    "degrees",
    "deltaTime",
    "describe",
    "describeElement",
    "deviceOrientation",
    "directionalLight",
    "displayDensity",
    "displayHeight",
    "displayWidth",
    "dist",
    "downloadFile",
    "ellipse",
    "ellipseMode",
    "ellipsoid",
    "emissiveMaterial",
    "encodeAndDownloadGif",
    "endClip",
    "endContour",
    "endGeometry",
    "endShape",
    "erase",
    "exitPointerLock",
    "exp",
    "fill",
    "filter",
    "float",
    "floor",
    "focused",
    "fract",
    "frameCount",
    "frameRate",
    "freeGeometry",
    "frustum",
    "fullscreen",
    "get",
    "getFilterGraphicsLayer",
    "getFrameRate",
    "getItem",
    "getTargetFrameRate",
    "getURL",
    "getURLParams",
    "getURLPath",
    "green",
    "gridOutput",
    "height",
    "hex",
    "hour",
    "httpDo",
    "httpGet",
    "httpPost",
    "hue",
    "image",
    "imageLight",
    "imageMode",
    "int",
    "isKeyPressed",
    "isLooping",
    "join",
    "key",
    "keyCode",
    "keyIsDown",
    "keyIsPressed",
    "lerp",
    "lerpColor",
    "lightFalloff",
    "lightness",
    "lights",
    "line",
    "linePerspective",
    "loadBytes",
    "loadFont",
    "loadImage",
    "loadJSON",
    "loadModel",
    "loadPixels",
    "loadShader",
    "loadStrings",
    "loadTable",
    "loadXML",
    "log",
    "loop",
    "mag",
    "map",
    "match",
    "matchAll",
    "max",
    "metalness",
    "millis",
    "min",
    "minute",
    "model",
    "month",
    "mouseButton",
    "mouseIsPressed",
    "mouseX",
    "mouseY",
    "movedX",
    "movedY",
    "nf",
    "nfc",
    "nfp",
    "nfs",
    "noCanvas",
    "noCursor",
    "noDebugMode",
    "noErase",
    "noFill",
    "noLights",
    "noLoop",
    "noSmooth",
    "noStroke",
    "noTint",
    "noise",
    "noiseDetail",
    "noiseSeed",
    "norm",
    "normal",
    "normalMaterial",
    "orbitControl",
    "ortho",
    "pAccelerationX",
    "pAccelerationY",
    "pAccelerationZ",
    "pRotateDirectionX",
    "pRotateDirectionY",
    "pRotateDirectionZ",
    "pRotationX",
    "pRotationY",
    "pRotationZ",
    "panorama",
    "perspective",
    "pixelDensity",
    "pixels",
    "plane",
    "pmouseX",
    "pmouseY",
    "point",
    "pointLight",
    "pop",
    "popMatrix",
    "popStyle",
    "pow",
    "print",
    "push",
    "pushMatrix",
    "pushStyle",
    "pwinMouseX",
    "pwinMouseY",
    "quad",
    "quadraticVertex",
    "radians",
    "random",
    "randomGaussian",
    "randomSeed",
    "rect",
    "rectMode",
    "red",
    "redraw",
    "registerPromisePreload",
    "removeElements",
    "removeItem",
    "requestPointerLock",
    "resetMatrix",
    "resetShader",
    "resizeCanvas",
    "reverse",
    "rotate",
    "rotateX",
    "rotateY",
    "rotateZ",
    "rotationX",
    "rotationY",
    "rotationZ",
    "round",
    "saturation",
    "save",
    "saveCanvas",
    "saveFrames",
    "saveGif",
    "saveJSON",
    "saveJSONArray",
    "saveJSONObject",
    "saveStrings",
    "saveTable",
    "scale",
    "second",
    "select",
    "selectAll",
    "set",
    "setAttributes",
    "setCamera",
    "setFrameRate",
    "setMoveThreshold",
    "setShakeThreshold",
    "shader",
    "shearX",
    "shearY",
    "shininess",
    "shorten",
    "shuffle",
    "sin",
    "smooth",
    "sort",
    "specularColor",
    "specularMaterial",
    "sphere",
    "splice",
    "split",
    "splitTokens",
    "spotLight",
    "sq",
    "sqrt",
    "square",
    "storeItem",
    "str",
    "stroke",
    "strokeCap",
    "strokeJoin",
    "strokeWeight",
    "subset",
    "tan",
    "text",
    "textAlign",
    "textAscent",
    "textDescent",
    "textFont",
    "textLeading",
    "textOutput",
    "textSize",
    "textStyle",
    "textWidth",
    "textWrap",
    "texture",
    "textureMode",
    "textureWrap",
    "tint",
    "torus",
    "touches",
    "translate",
    "triangle",
    "trim",
    "turnAxis",
    "unchar",
    "unhex",
    "updatePixels",
    "vertex",
    "webglVersion",
    "width",
    "winMouseX",
    "winMouseY",
    "windowHeight",
    "windowWidth",
    "writeFile",
    "year"
]

const ADD="lighter"
const ALT=18
const ARROW="default"
const AUDIO="audio"
const AUTO="auto"
const AXES="axes"
const BACKSPACE=8
const BASELINE="alphabetic"
const BEVEL="bevel"
const BEZIER="bezier"
const BLEND="source-over"
const BLUR="blur"
const BOLD="bold"
const BOLDITALIC="bold italic"
const BOTTOM="bottom"
const BURN="color-burn"
const CENTER="center"
const CHAR="CHAR"
const CHORD="chord"
const CLAMP="clamp"
const CLOSE="close"
const CONTAIN="contain"
const CONTROL=17
const CORNER="corner"
const CORNERS="corners"
const COVER="cover"
const CROSS="crosshair"
const CURVE="curve"
const DARKEST="darken"
const DEGREES="degrees"
const DEG_TO_RAD=0.017453292519943295
const DELETE=46
const DIFFERENCE="difference"
const DILATE="dilate"
const DODGE="color-dodge"
const DOWN_ARROW=40
const ENTER=13
const ERODE="erode"
const ESCAPE=27
const EXCLUSION="exclusion"
const FALLBACK="fallback"
const FILL="fill"
const FLAT="flat"
const FLOAT="float"
const GRAY="gray"
const GRID="grid"
const HALF_FLOAT="half-float"
const HALF_PI=1.5707963267948966
const HAND="pointer"
const HARD_LIGHT="hard-light"
const HSB="hsb"
const HSL="hsl"
const IMAGE="image"
const IMMEDIATE="immediate"
const INVERT="invert"
const ITALIC="italic"
const LABEL="label"
const LANDSCAPE="landscape"
const LEFT="left"
const LEFT_ARROW=37
const LIGHTEST="lighten"
const LINEAR="linear"
const LINES=1
const LINE_LOOP=2
const LINE_STRIP=3
const MIRROR="mirror"
const MITER="miter"
const MOVE="move"
const MULTIPLY="multiply"
const NEAREST="nearest"
const NORMAL="normal"
const OPAQUE="opaque"
const OPEN="open"
const OPTION=18
const OVERLAY="overlay"
const P2D="p2d"
const PI=3.141592653589793
const PIE="pie"
const POINTS=0
const PORTRAIT="portrait"
const POSTERIZE="posterize"
const PROJECT="square"
const QUADRATIC="quadratic"
const QUADS="quads"
const QUAD_STRIP="quad_strip"
const QUARTER_PI=0.7853981633974483
const RADIANS="radians"
const RADIUS="radius"
const RAD_TO_DEG=57.29577951308232
const REMOVE="destination-out"
const REPEAT="repeat"
const REPLACE="copy"
const RETURN=13
const RGB="rgb"
const RGBA="rgba"
const RIGHT="right"
const RIGHT_ARROW=39
const ROUND="round"
const SCREEN="screen"
const SHIFT=16
const SMOOTH="smooth"
const SOFT_LIGHT="soft-light"
const SQUARE="butt"
const STROKE="stroke"
const SUBTRACT="subtract"
const TAB=9
const TAU=6.283185307179586
const TESS="tess"
const TEXT="text"
const TEXTURE="texture"
const THRESHOLD="threshold"
const TOP="top"
const TRIANGLES=4
const TRIANGLE_FAN=6
const TRIANGLE_STRIP=5
const TWO_PI=6.283185307179586
const UNSIGNED_BYTE="unsigned-byte"
const UNSIGNED_INT="unsigned-int"
const UP_ARROW=38
const VERSION="1.9.4"
const VIDEO="video"
const WAIT="wait"
const WEBGL="webgl"
const WEBGL2="webgl2"
const WORD="WORD"